spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EZBank Cards related QA APIs "
  contactDetails:
    name: "joe Rai - QA Lead"
    email: "joe@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371